<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>OfficeMasking.Core</RootNamespace>
    <AssemblyName>OfficeMasking.Core</AssemblyName>
    <LangVersion>7.3</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="OfficeMasking.Core.Tests" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
</Project>
